[package]
name = "nnis-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "NVIDIA Native Inference Stack"

[dependencies]
nnis-rt = { workspace = true }
nnis-sys = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
nnis-jit = { workspace = true }
nnis-kernels = { workspace = true }
