[package]
name = "nnis-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Command-line generation frontend for NNIS"
publish = false

[[bin]]
name = "nnis"
path = "src/main.rs"

[[bin]]
name = "nnis-hf"
path = "src/bin/nnis-hf.rs"

[dependencies]
nnis = { path = "../nnis" }
nnis-model = { path = "../nnis-model" }
serde_json = { workspace = true }
tokenizers = { version = "=0.19.1", default-features = false, features = ["unstable_wasm"] }
