#!/usr/bin/env python3
"""Machine-readable NNIS license/provenance inventory.

This tool inventories evidence that matters before any repository relicensing.
It deliberately does not decide ownership, contributor consent, or whether a
historical license grant can be revoked. Those conclusions require evidence
outside a source-tree scan and therefore remain human/legal review items.
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import re
import subprocess
import tempfile
from typing import Iterable

SCHEMA_VERSION = 1
TEXT_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cu",
    ".cuh",
    ".h",
    ".hpp",
    ".json",
    ".md",
    ".py",
    ".rs",
    ".sh",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
}
LICENSE_NAMES = {"license", "copying", "notice", "authors"}
REVIEW_PATH_COMPONENTS = {
    "vendor",
    "vendors",
    "vendored",
    "third_party",
    "third-party",
    "generated",
}
EXTERNAL_MARKERS = (
    "nvidia",
    "hugging face",
    "huggingface",
    "adapted from",
    "copied from",
    "generated by",
)


class AuditError(RuntimeError):
    pass


def _git(root: pathlib.Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(root), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if completed.returncode != 0:
        raise AuditError(
            f"git {' '.join(args)} failed ({completed.returncode}): "
            f"{completed.stderr.strip()}"
        )
    return completed.stdout


def _tracked_files(root: pathlib.Path) -> list[str]:
    raw = _git(root, "ls-files", "-z")
    return sorted(path for path in raw.split("\0") if path)


def _contributors(root: pathlib.Path) -> list[dict[str, object]]:
    raw = _git(root, "log", "--format=%aN%x1f%aE")
    counts: collections.Counter[tuple[str, str]] = collections.Counter()
    for line in raw.splitlines():
        if "\x1f" not in line:
            continue
        name, email = line.split("\x1f", 1)
        counts[(name.strip(), email.strip())] += 1
    return [
        {"name": name, "email": email, "authored_commits": count}
        for (name, email), count in sorted(
            counts.items(), key=lambda item: (-item[1], item[0][0], item[0][1])
        )
    ]


def _is_license_like(path: str) -> bool:
    name = pathlib.PurePosixPath(path).name.lower()
    stem = name.split(".", 1)[0]
    return stem in LICENSE_NAMES or name.startswith("license-")


def _manifest_license_metadata(text: str) -> dict[str, list[str]]:
    license_values = re.findall(
        r'(?m)^\s*license\s*=\s*"([^"]+)"\s*(?:#.*)?$', text
    )
    license_files = re.findall(
        r'(?m)^\s*license-file\s*=\s*"([^"]+)"\s*(?:#.*)?$', text
    )
    return {
        "license_values": license_values,
        "license_files": license_files,
    }


def _safe_text(path: pathlib.Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def _source_markers(root: pathlib.Path, tracked: Iterable[str]) -> dict[str, object]:
    spdx_files: list[str] = []
    copyright_files: list[str] = []
    review_candidates: list[dict[str, object]] = []

    for relative in tracked:
        path = pathlib.PurePosixPath(relative)
        if path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        text = _safe_text(root / relative)
        if text is None:
            continue
        lowered = text.lower()
        if "spdx-license-identifier:" in lowered:
            spdx_files.append(relative)
        if "copyright" in lowered:
            copyright_files.append(relative)

        matched = [marker for marker in EXTERNAL_MARKERS if marker in lowered]
        if matched:
            review_candidates.append(
                {
                    "path": relative,
                    "markers": matched,
                }
            )

    return {
        "spdx_files": sorted(spdx_files),
        "copyright_files": sorted(copyright_files),
        "external_marker_review_candidates": review_candidates,
    }


def _review_paths(tracked: Iterable[str]) -> list[str]:
    result: list[str] = []
    for relative in tracked:
        parts = {part.lower() for part in pathlib.PurePosixPath(relative).parts}
        if parts & REVIEW_PATH_COMPONENTS:
            result.append(relative)
    return sorted(result)


def build_report(root: pathlib.Path) -> dict[str, object]:
    root = root.resolve()
    if not (root / ".git").exists():
        raise AuditError(f"{root} is not a Git working tree root")

    tracked = _tracked_files(root)
    head = _git(root, "rev-parse", "HEAD").strip()
    status = _git(root, "status", "--porcelain=v1")
    license_like = sorted(path for path in tracked if _is_license_like(path))
    root_license_like = [
        path for path in license_like if "/" not in pathlib.PurePosixPath(path).as_posix()
    ]

    manifests: list[dict[str, object]] = []
    for relative in tracked:
        if pathlib.PurePosixPath(relative).name != "Cargo.toml":
            continue
        text = _safe_text(root / relative)
        if text is None:
            continue
        metadata = _manifest_license_metadata(text)
        manifests.append(
            {
                "path": relative,
                **metadata,
            }
        )

    markers = _source_markers(root, tracked)
    report = {
        "schema_version": SCHEMA_VERSION,
        "repository_root": str(root),
        "git_head": head,
        "git_dirty": bool(status.strip()),
        "tracked_file_count": len(tracked),
        "contributors": _contributors(root),
        "license_notice_files": license_like,
        "root_license_notice_files": root_license_like,
        "cargo_manifests": manifests,
        "vendored_generated_review_paths": _review_paths(tracked),
        **markers,
        "automatic_relicensing_ready": False,
        "automatic_relicensing_ready_reason": (
            "A source-tree audit cannot establish complete copyright ownership, "
            "contributor consent, or the legal effect of prior license grants."
        ),
        "required_human_review": [
            "verify rights or consent for every contributor-owned change",
            "review copied/adapted/imported code and third-party notices",
            "preserve prior license grants and third-party obligations",
            "decide any future license change only from documented rights evidence",
        ],
    }
    return report


def _self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="nnis-license-audit-") as raw:
        root = pathlib.Path(raw)
        subprocess.run(["git", "init", "-q", str(root)], check=True)
        (root / "src").mkdir()
        (root / "Cargo.toml").write_text(
            '[package]\nname = "fixture"\nversion = "0.1.0"\nlicense = "MIT"\n',
            encoding="utf-8",
        )
        (root / "src" / "lib.rs").write_text(
            "// Copyright 2026 Example\n"
            "// SPDX-License-Identifier: MIT\n"
            "pub fn fixture() {}\n",
            encoding="utf-8",
        )
        subprocess.run(["git", "-C", str(root), "add", "."], check=True)
        subprocess.run(
            [
                "git",
                "-C",
                str(root),
                "-c",
                "user.name=Audit Fixture",
                "-c",
                "user.email=audit@example.invalid",
                "commit",
                "-q",
                "-m",
                "fixture",
            ],
            check=True,
        )
        report = build_report(root)
        assert report["schema_version"] == 1
        assert report["tracked_file_count"] == 2
        assert report["automatic_relicensing_ready"] is False
        assert report["root_license_notice_files"] == []
        assert report["cargo_manifests"][0]["license_values"] == ["MIT"]
        assert report["spdx_files"] == ["src/lib.rs"]
        assert report["copyright_files"] == ["src/lib.rs"]
        assert report["contributors"][0]["name"] == "Audit Fixture"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Git working tree root")
    parser.add_argument("--output", help="Write JSON report to this path")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        _self_test()
        print("license provenance audit self-test: OK")
        return 0

    report = build_report(pathlib.Path(args.root))
    rendered = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if args.output:
        pathlib.Path(args.output).write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
